Repository openshift/monitor-project-lifecycle, pull requests merged in 2018-04, with the labels that each got.

#13 Add reading in a config file.
  cmd/monitor/monitor.go
Labels: lgtm, size/M

#16 Add route check, make step completions optional and non-fatal on error
  cmd/monitor/monitor.go
  stepwatcher/stepwatcher.go
Labels: size/L

#17 Switch to glog and other fixes
  cmd/monitor/config.yaml
  cmd/monitor/monitor.go
Labels: lgtm, size/M

#18 Make config file a required flag
  Gopkg.lock
  cmd/monitor/main.go
  cmd/monitor/monitor.go
  install/manifests/config.yaml
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/LICENSE.golden
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/zsh_completions.go
Labels: lgtm, size/XXL

#19 Clean up configuration struct
  cmd/monitor/monitor.go
  install/manifests/config.yaml
Labels: lgtm, size/M

#20 Refactor to support primary use case
  Gopkg.lock
  README.md
  client/client.go
  cmd/monitor/config.go
  cmd/monitor/main.go
  cmd/monitor/monitor.go
  install/hack/deploy
  install/manifests/config.yaml
  install/manifests/lifecycle-app.yaml
Labels: lgtm, size/XL

#21 Add essential metrics
  cmd/monitor/monitor.go
Labels: lgtm, size/M
